# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}   # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity check
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          test -f index.html && echo "found index.html" || (echo "missing index.html" && exit 1)
          test -f 404.html && echo "found 404.html" || (echo "missing 404.html" && exit 1)
